sudo: false
git:
  depth: 3
language: java
matrix:
  include:
  - name: Oracle JDK 8 on Trusty
    # using `openjdk8` leads to javadoc errors
    jdk: oraclejdk8
    dist: trusty # oraclejdk8 absent in Xenial
  - name: OpenJDK 11
    jdk: openjdk11
  - name: OpenJDK 14 (Gradle 6.5)
    jdk: openjdk14
    script:
    - wget https://services.gradle.org/distributions/gradle-6.5-bin.zip
    - unzip gradle-6.5-bin.zip
    - ./gradle-6.5/bin/gradle clean build --stacktrace

env:
  global:
  - TERM=dumb         # for gradle

install: true
script:
- ./gradlew clean build --stacktrace

# cobbled together from
#   https://docs.travis-ci.com/user/languages/java/#projects-using-gradle
#   https://github.com/blox/blox/pull/338#issuecomment-358556137
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/fileHashes/
- rm -fr $HOME/.gradle/caches/jars-3/
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
